export const SET_LOADING = "SET_LOADING"
export const SET_USER_DATA = "SET_USER_DATA"
export const CLEAR_USER_DATA = "CLEAR_USER_DATA"
export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const AUTH_ERROR = "AUTH_ERROR"
